name: healie
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_system_icons: ^1.1.225
  flutter_chat_ui: ^1.6.10
  intl: ^0.19.0
  replicate: ^1.0.0
  dio: ^5.4.0
  flutter_riverpod: ^2.4.9
  flutter_chat_types: ^3.6.2
  bard_api: ^1.0.0
  flutter_hooks: ^0.20.4
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
